apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-0uzs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-0uzs
    app.kubernetes.io/part-of: tkrw-pr714-0075-0056-app
  name: devfile-sample-0uzs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-0uzs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-0uzs
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0056-tenant/tkrw-pr714-0075-0056-app/devfile-sample-0uzs@sha256:fe3a9f2fefa91fa2559c3fcff48698e2c34839f81b1d3985e38418716ec95096
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
